//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RobotInterfaces
{
    [Serializable]
    public class ExcavationPointMsg : Message
    {
        public const string k_RosMessageName = "robot_interfaces/ExcavationPoint";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float z;
        public int type;
        public string id;

        public ExcavationPointMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.type = 0;
            this.id = "";
        }

        public ExcavationPointMsg(float x, float y, float z, int type, string id)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.type = type;
            this.id = id;
        }

        public static ExcavationPointMsg Deserialize(MessageDeserializer deserializer) => new ExcavationPointMsg(deserializer);

        private ExcavationPointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.type);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.type);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "ExcavationPointMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\ntype: " + type.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
