//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Messages
{
    [Serializable]
    public class GoalsMsg : Message
    {
        public const string k_RosMessageName = "Messages/Goals";
        public override string RosMessageName => k_RosMessageName;

        //  An array of navigation goals
        //  This header will store the time at which the poses were computed (not to be confused with the stamps of the poses themselves)
        //  In the case that individual poses do not have their frame_id set or their timetamp set they will use the default value here.
        public Std.HeaderMsg header;
        //  An array of goals to for navigation to achieve.
        //  The goals should be executed in the order of the array.
        //  The header and stamp are intended to be used for computing the position of the goals.
        //  They may vary to support cases of goals that are moving with respect to the robot.
        public Geometry.PoseStampedMsg[] goals;

        public GoalsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.goals = new Geometry.PoseStampedMsg[0];
        }

        public GoalsMsg(Std.HeaderMsg header, Geometry.PoseStampedMsg[] goals)
        {
            this.header = header;
            this.goals = goals;
        }

        public static GoalsMsg Deserialize(MessageDeserializer deserializer) => new GoalsMsg(deserializer);

        private GoalsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.goals, Geometry.PoseStampedMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.goals);
            serializer.Write(this.goals);
        }

        public override string ToString()
        {
            return "GoalsMsg: " +
            "\nheader: " + header.ToString() +
            "\ngoals: " + System.String.Join(", ", goals.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
